version: 2

jobs:
  build:
    working_directory: ~/Attendance
    docker:
      - image: node:12.16.1
    steps:
      - checkout
      - run:
          name: update-npm
          command: npm install -g npm@latest
      - run:
          name: install-npm-wee
          command: npm install
      - run:
          name: code check
          command: npm run lint

  deploy:
    machine:
      enabled: true
    steps:
      - add_ssh_keys:  
          fingerprints:  
            - $SSHKEY_FINGERPRINT
      - run:  
          name: start ssh-keyscan  
          command: ssh-keyscan -p $SSH_PORT $SSH_HOST >> ~/.ssh/known_hosts
      - run:
          name: start deploy
          command: ssh -p $SSH_PORT $SSH_USER@$SSH_HOST "sh ~/Attendance/script/deploy.sh"

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
