version: 2

jobs:
  build:
    working_directory: ~/Attendance

    docker:
      - image: node:12.16.1

    steps:
      - checkout
      - run:
          name: update-npm
          command: npm install -g npm@latest
      - run:
          name: install-npm-wee
          command: npm install
      - run:
          name: code check
          command: npm run lint
