version: 2.1

orbs:
  slack: circleci/slack@3.4.2

jobs:
  build:
    working_directory: ~/Attendance
    docker:
      - image: node:12.16.1
    steps:
      - checkout
      - run:
          name: update-npm
          command: npm install -g npm@latest
      - run:
          name: install-npm-wee
          command: npm install
      - run:
          name: code check
          command: npm run lint

  deploy:
    machine:
      enabled: true
    steps:
      - add_ssh_keys:  
          fingerprints:  
            - $SSHKEY_FINGERPRINT
      - run:  
          name: start ssh-keyscan  
          command: ssh-keyscan -p $SSH_PORT $SSH_HOST >> ~/.ssh/known_hosts
      - run:
          name: start deploy
          command: ssh -p $SSH_PORT $SSH_USER@$SSH_HOST "sh ~/Attendance/.circleci/deploy.sh"

  notification:
    steps:
      - slack/status:
          success_message: ':circleci-pass: $CIRCLE_BRANCH のデプロイが完了しました\n:github_octocat: User：$CIRCLE_USERNAME'
          failure_message: ':circleci-fail: $CIRCLE_BRANCH のデプロイが失敗しました\n:github_octocat: User：$CIRCLE_USERNAME'
          webhook: '${SLACK_WEBHOOK}'
    

workflows:
  version: 2
  build-and-deploy-and-notification:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
      - notification:
          requires:
            - deploy
